service: sample-serverless

custom:
  config: ${file(./config.yml)}
  # config: ${file(config.yml)}
  appName: ${self:custom.config.app.name}
  regionConfig: ${self:custom.config.regions.${self:provider.region}, self:custom.config.regions.default}
  keyName: key-${self:provider.region}  # ✅ Dynamic KeyPair

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'ap-south-2'}
  stage: ${opt:stage, 'prod'}

  environment:
    TABLE_NAME: ${self:custom.appName}-table-${self:provider.region}
    BUCKET_NAME: ${self:custom.appName}-bucket-${self:provider.region}

    # TABLE_NAME: serverless-cdktable-${self:provider.region}
    # BUCKET_NAME: serverless-cdk-${self:provider.region}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.appName}-table-${self:provider.region}

        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            Fn::Sub: arn:aws:s3:::my-serverless-bucket-${self:provider.stage}-${AWS::AccountId}-${AWS::Region}/*

        - Effect: Allow
          Action:
            - logs:*
          Resource: "*"

  vpc:
    securityGroupIds:
      - !Ref LambdaSecurityGroup
    subnetIds:
      - !Ref PrivateSubnet1

functions:
  hello:
    handler: handler.hello
    timeout: 10
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:

    # ---------------- VPC ----------------
    MyVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: ${self:custom.regionConfig.cidr}
        # CidrBlock: ${self:custom.config.regions.${self:custom.region}.cidr}
        Tags:
          - Key: Name
            Value: ${self:custom.appName}-${self:provider.region}-vpc

    # ---------------- INTERNET GATEWAY ----------------
    InternetGateway:
      Type: AWS::EC2::InternetGateway

    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId: !Ref MyVPC
        InternetGatewayId: !Ref InternetGateway

    # ---------------- PUBLIC SUBNET ----------------
    PublicSubnet:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: ${self:custom.regionConfig.publicSubnet}
        # CidrBlock: ${self:custom.config.regions.${opt:region}.cidr}
        MapPublicIpOnLaunch: true
        AvailabilityZone:
          Fn::Select:
            - 0
            - Fn::GetAZs: ""

    PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref MyVPC

    PublicRoute:
      Type: AWS::EC2::Route
      DependsOn: AttachGateway
      Properties:
        RouteTableId: !Ref PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway

    PublicSubnetRouteTableAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId: !Ref PublicSubnet
        RouteTableId: !Ref PublicRouteTable

    # ---------------- PRIVATE SUBNET ----------------
    PrivateSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: ${self:custom.regionConfig.privateSubnet}
        AvailabilityZone:
          Fn::Select:
            - 0
            - Fn::GetAZs: ""

    # ---------------- SECURITY GROUPS ----------------

    BastionSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Bastion SG
        VpcId: !Ref MyVPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 49.204.141.47/32   # 🔥 CHANGE YOUR IP

    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Lambda SG
        VpcId: !Ref MyVPC
        SecurityGroupIngress:
          - IpProtocol: -1
            SourceSecurityGroupId: !Ref BastionSecurityGroup

    # ---------------- BASTION EC2 ----------------
    BastionHost:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: ${self:custom.regionConfig.instanceType}
        SubnetId: !Ref PublicSubnet
        SecurityGroupIds:
          - !Ref BastionSecurityGroup
        ImageId:
          Fn::Sub: "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}"
        KeyName: ${self:custom.keyName}
        Tags:
          - Key: Name
            Value: ${self:custom.appName}-${self:provider.region}-bastion

    # ---------------- S3 ----------------
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName:
          Fn::Sub: ${self:custom.appName}-${self:provider.stage}-${AWS::AccountId}-${AWS::Region}

    # ---------------- DynamoDB ----------------
    MyDynamoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.appName}-${self:provider.region}-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

  Outputs:
    BucketName:
      Value: !Ref MyS3Bucket

    TableName:
      Value: !Ref MyDynamoTable

    BastionPublicIP:
      Value: !GetAtt BastionHost.PublicIp